### ISSUE TITLE
 Call to undefined function mb_strcut() 

### ISSUE THREAD

**Issue by windanchaos** [ycmbcd/md-Blog#7]
在/set/admin.html 页面

软件设置：
未开启：畅言评论设置、百度统计
在md目录下新建文件夹xxx，并在该文件夹下上传了2个md文件。

点击页面的‘全站静态生成’按钮后，在代码路生成了blog目录，目录空文件夹1和2 、html，文件header.html ，文件html/16874442627141.html

nginx日志出错：
```
2023/06/22 07:37:42 [error] 94734#0: *207 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: side_list in /home/root/md-Blog/set/api/make_html.php on line 80
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_strcut() in /home/root/md-Blog/set/api/read_item.php:107
Stack trace:
#0 /home/root/md-Blog/set/api/read_md.php(34): read_item(Array)
#1 /home/root/md-Blog/set/api/run.php(43): read_md('../../blog/2')
#2 {main}
  thrown in /home/root/md-Blog/set/api/read_item.php on line 107" while reading response header from upstream, client: 192.168.91.1, server: _, request: "POST /set/api/run.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "192.168.91.129", referrer: "http://192.168.91.129/set/admin.html"
```

环境：
  OS:  centOS8.5_x64_x86
  php: PHP 7.2.24
  nginx/1.14.1

**Comment by windanchaos** [comment]
evi problem
```
dnf install -y php-mbstring
```
